//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmacenesEntities : DbContext
    {
        public AlmacenesEntities()
            : base("name=AlmacenesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCargo> tCargo { get; set; }
        public virtual DbSet<tDetalleMaterial> tDetalleMaterial { get; set; }
        public virtual DbSet<tDetalleSolicitud> tDetalleSolicitud { get; set; }
        public virtual DbSet<tMaterial> tMaterial { get; set; }
        public virtual DbSet<tPersona> tPersona { get; set; }
        public virtual DbSet<tReseteoContraseña> tReseteoContraseña { get; set; }
        public virtual DbSet<tSolicitud> tSolicitud { get; set; }
        public virtual DbSet<tTipo> tTipo { get; set; }
        public virtual DbSet<tTipoSolicitud> tTipoSolicitud { get; set; }
        public virtual DbSet<tUnidad> tUnidad { get; set; }
        public virtual DbSet<tUsuario> tUsuario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tDepartamento> tDepartamento { get; set; }
    }
}
