//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleSolicitud
    {
        public int Id { get; set; }
        public Nullable<int> Idsolicitud { get; set; }
        public Nullable<int> IdDetalleMaterial { get; set; }
        public Nullable<int> CantidadSolicitada { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> CantidadAprobada { get; set; }
        public string Especificacion { get; set; }
    
        public virtual tDetalleMaterial tDetalleMaterial { get; set; }
        public virtual tSolicitud tSolicitud { get; set; }
    }
}
